export const initialPatients = [
  {
    id: 1,
    name: "John Doe",
    age: 45,
    gender: "Male",
    contact: "123-456-7890",
    email: "john@example.com",
    bloodGroup: "O+",
    status: "ongoing",
    diagnosis: "Hypertension",
    lastVisit: "2024-12-15",
    medications: ["Lisinopril 10mg", "Aspirin 81mg"],
    allergies: ["Penicillin"],
    notes: "Patient showing improvement with current medication",
    followUps: [
      {
        date: "2024-12-20",
        reason: "Blood pressure check",
        status: "scheduled",
      },
      {
        date: "2024-11-15",
        reason: "Initial consultation",
        status: "completed",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 32,
    gender: "Female",
    contact: "098-765-4321",
    email: "jane@example.com",
    bloodGroup: "A+",
    status: "resolved",
    diagnosis: "Seasonal Allergies",
    lastVisit: "2024-11-20",
    medications: ["Cetirizine 10mg"],
    allergies: ["None"],
    notes: "Symptoms fully resolved",
    followUps: [
      { date: "2024-11-20", reason: "Follow-up check", status: "completed" },
    ],
  },
  {
    id: 3,
    name: "Michael Brown",
    age: 58,
    gender: "Male",
    contact: "555-123-4567",
    email: "michael@example.com",
    bloodGroup: "B-",
    status: "ongoing",
    diagnosis: "Type 2 Diabetes",
    lastVisit: "2024-12-18",
    medications: ["Metformin 500mg", "Glimepiride 2mg"],
    allergies: ["Sulfa drugs"],
    notes: "Blood sugar levels stabilizing",
    followUps: [
      {
        date: "2025-01-10",
        reason: "Diabetes management review",
        status: "scheduled",
      },
    ],
  },
];
